Fix building with `-fno-common`
This is the default in gcc 10 & later, and causes build failures with:
/usr/sbin/ld: .libs/xgi_driver.o:/builds/alanc/xf86-video-xgi/_builddir/src/../../src/xgi_accel.h:125: multiple definition of `Alignment'; .libs/xgi_accel.o:/builds/alanc/xf86-video-xgi/_builddir/src/../../src/xgi_accel.h:125: first defined here
/usr/sbin/ld: .libs/xgi_driver.o:/builds/alanc/xf86-video-xgi/_builddir/src/../../src/xgi_accel.h:124: multiple definition of `G2CmdQueLen'; .libs/xgi_accel.o:/builds/alanc/xf86-video-xgi/_builddir/src/../../src/xgi_accel.h:124: first defined here
/usr/sbin/ld: .libs/xgi_driver.o:/builds/alanc/xf86-video-xgi/_builddir/src/../../src/xgi_accel.h:122: multiple definition of `w_port'; .libs/xgi_accel.o:/builds/alanc/xf86-video-xgi/_builddir/src/../../src/xgi_accel.h:122: first defined here
/usr/sbin/ld: .libs/xgi_driver.o:/builds/alanc/xf86-video-xgi/_builddir/src/../../src/xgi_accel.h:122: multiple definition of `r_port'; .libs/xgi_accel.o:/builds/alanc/xf86-video-xgi/_builddir/src/../../src/xgi_accel.h:122: first defined here

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>