fix conflict on redefinition of `bool`
  In file included from xgi.h:154,
                   from vb_ext.c:30:
  vgatypes.h:119:15: error: two or more data types in declaration specifiers
    119 | typedef UCHAR bool;
        |               ^~~~

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>