fix FTBS on missing typedef ulong
> ../../src/xgi_accel.c: In function 'XGIPrepareSolid':
> ../../src/xgi_accel.h:382:27: error: 'ulong' undeclared (first use in this function); did you mean 'ULong'?
>   382 |     pXGI->CommandReg |= ((ulong)(bpp))&(GENMASK(17:16)) ;
>       |                           ^~~~~

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
Part-of: <https://gitlab.freedesktop.org/xorg/driver/xf86-video-xgi/-/merge_requests/8>