fix FTBS on missing return value
> ../../src/xgi_accel.c:1055:2: error: non-void function 'XGIUploadToScratch' should return a value [-Wreturn-type]
         DisableDrawingFunctionDynamically(TRUE);
>         ^
> ../../src/xgi_accel.c:185:4: note: expanded from macro 'DisableDrawingFunctionDynamically'
>                         return; \
>                         ^

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>
Part-of: <https://gitlab.freedesktop.org/xorg/driver/xf86-video-xgi/-/merge_requests/8>